### ISSUE TITLE
Throws error when sorting data

### ISSUE THREAD

**Issue by leggsimon** [schwamic/klangspektrum#2]
[This line](https://github.com/schwamic/klangspektrum/blob/797af6834c034c8359747153eade475e79d0205d/src/Viz/Controller/timeEvents.js#L25) throws with `Cannot read property 'top' of undefined` and then hangs on 
```
Hello <username>, this could take a little while.

sort data
```

**Comment by schwamic** [comment]
new version: https://github.com/schwamic/klangspektrum2
